# Generated by Django 5.1.4 on 2024-12-16 06:12

from django.db import migrations

def update_phone_and_joined_date(apps, schema_editor):
    Member = apps.get_model('members', 'Member')
    Member.objects.all().update(phone=1234567890, joined_date='2024-12-16') 

class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.RunPython(update_phone_and_joined_date),
    ]
