apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app-with-nginx
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/container-dependencies: '{"nginx-sidecar":["app"]}' 
    spec:
      containers:
      - name: app
        image: asia-northeast1-docker.pkg.dev/yorikane-alto-dev/demo/simple-fast-api:latest
        startupProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
      - name: nginx-sidecar
        image: asia-northeast1-docker.pkg.dev/yorikane-alto-dev/demo/nginx-proxy-8080:latest
        ports:
        - containerPort: 80 
