version: "3.8"

services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - nginx

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      API_KEY: demo
