version: "3.8"

services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      API_KEY: demo
      BACKEND_HOST: app
    command: /bin/sh -c "envsubst '$$BACKEND_HOST$$API_KEY' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - app
