version: '3'

services:

  postgres:
    container_name: postgres
    image: postgres:15
    ports:
      - 5432:5432
    restart: always
    volumes:
       - postgres:/data/postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /data/postgres
 
  app:
    container_name: app
    build: .
    links:
      - "mysql"
    depends_on:
      - "mysql"
    ports:
      - 8080:8080
    environment:
      INSTANCE_HOST: mysql
      DB_USER: user
      DB_PASS: password
      DB_NAME: db
      DB_PORT: 3306
    networks:
      - app-net

volumes:
    postgres:
