services:

  postgres:
    container_name: postgres
    image: postgres:15
    ports:
      - 5432:5432
    restart: always
    volumes:
       - postgres:/data/postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /data/postgres
 
  app:
    container_name: app
    build: .
    links:
      - "postgres"
    depends_on:
      - "postgres"
    ports:
      - 8080:8080
    env_file:
      - "local.env"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: postgres
      # -- SET variables to local.env
      # TMP_UPLOAD_BUCKET_NAME: "" 
      # PERSISTIBLE_BUCKET_NAME: ""
      # SENDGRID_API_KEY: ""

volumes:
    postgres:
