# Google Cloud Build 設定ファイル
steps:
  # Docker イメージのビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/manzai-tsukkomi-app:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/manzai-tsukkomi-app:latest',
      '.'
    ]

  # Container Registry にプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/manzai-tsukkomi-app:$BUILD_ID']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/manzai-tsukkomi-app:latest']

  # Cloud Run にデプロイ
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'manzai-tsukkomi-app',
      '--image', 'gcr.io/$PROJECT_ID/manzai-tsukkomi-app:$BUILD_ID',
      '--region', 'asia-northeast1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '2Gi',
      '--cpu', '2',
      '--concurrency', '100',
      '--max-instances', '10',
      '--set-env-vars', 'GOOGLE_API_KEY=${_GOOGLE_API_KEY}',
      '--port', '8080'
    ]

# 環境変数の置換
substitutions:
  _GOOGLE_API_KEY: 'your-google-api-key-here'

# ビルドオプション
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# タイムアウト設定
timeout: '1200s'