services:
  postgres:
    container_name: postgres
    image: postgres:15
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres:/data/postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /data/postgres

  app:
    container_name: app
    build: .
    links:
      - "postgres"
    depends_on:
      - "postgres"
    ports:
      - 8000:8000
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: postgres

volumes:
  postgres:
